// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlO0DZnVPykLzXh3McE8SFQMYrEXuo5o',
    appId: '1:82222251863:web:e19e63d339b8132b550812',
    messagingSenderId: '82222251863',
    projectId: 'flutter-online-store-193614',
    authDomain: 'flutter-online-store-193614.firebaseapp.com',
    storageBucket: 'flutter-online-store-193614.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlwFxEoL0NitKBiVQyZvwhgpgdO3T_y9Q',
    appId: '1:82222251863:android:02cfe4ccf3f730b1550812',
    messagingSenderId: '82222251863',
    projectId: 'flutter-online-store-193614',
    storageBucket: 'flutter-online-store-193614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUKiNVZatbnsCNsG1S-fLqp6eZU_xOzQ',
    appId: '1:82222251863:ios:0f7d93b3ba24022c550812',
    messagingSenderId: '82222251863',
    projectId: 'flutter-online-store-193614',
    storageBucket: 'flutter-online-store-193614.firebasestorage.app',
    iosBundleId: 'com.example.flutterOnlineStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqUKiNVZatbnsCNsG1S-fLqp6eZU_xOzQ',
    appId: '1:82222251863:ios:0f7d93b3ba24022c550812',
    messagingSenderId: '82222251863',
    projectId: 'flutter-online-store-193614',
    storageBucket: 'flutter-online-store-193614.firebasestorage.app',
    iosBundleId: 'com.example.flutterOnlineStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlO0DZnVPykLzXh3McE8SFQMYrEXuo5o',
    appId: '1:82222251863:web:0f79c748cf51308a550812',
    messagingSenderId: '82222251863',
    projectId: 'flutter-online-store-193614',
    authDomain: 'flutter-online-store-193614.firebaseapp.com',
    storageBucket: 'flutter-online-store-193614.firebasestorage.app',
  );
}
